import {
  Server,
  Database,
  Monitor,
  Globe,
  Cloud,
  Shield,
  Code,
  Network,
  HardDrive,
  Cpu,
  Workflow,
  Box,
  Layers,
  Package,
  Puzzle,
  Key,
  Link,
  GitBranch,
  Zap,
  Lock,
  Bell,
  Activity,
  Home,
  Table,
  Router,
  Users,
  Mail,
  FileText,
  Search,
  type LucideIcon,
} from 'lucide-react';

export const DIAGRAM_ICONS: Record<string, LucideIcon> = {
  server: Server,
  database: Database,
  monitor: Monitor,
  globe: Globe,
  cloud: Cloud,
  shield: Shield,
  code: Code,
  network: Network,
  'hard-drive': HardDrive,
  cpu: Cpu,
  workflow: Workflow,
  box: Box,
  layers: Layers,
  package: Package,
  puzzle: Puzzle,
  key: Key,
  link: Link,
  'git-branch': GitBranch,
  zap: Zap,
  lock: Lock,
  bell: Bell,
  activity: Activity,
  home: Home,
  table: Table,
  router: Router,
  users: Users,
  mail: Mail,
  'file-text': FileText,
  search: Search,
};

/** Maps Architecture serviceType → default icon key */
export const SERVICE_TYPE_DEFAULTS: Record<string, string> = {
  API: 'server',
  Database: 'database',
  UI: 'monitor',
  External: 'globe',
  Cache: 'hard-drive',
  Queue: 'workflow',
  Auth: 'shield',
  Function: 'code',
  Cloud: 'cloud',
  Network: 'network',
  Gateway: 'router',
  Users: 'users',
  Email: 'mail',
  Storage: 'hard-drive',
  Search: 'search',
};

export const ICON_NAMES = Object.keys(DIAGRAM_ICONS);
